
env:
  - CODACY_PROJECT_TOKEN = 131944387b4a4e4aad2e1f08c10d69a9

language: android
android:
  components:
    - tools
    - build-tools-26.0.2
    - android-25
    - platform-tools
    - extra-android-support # because I'm use support library
    - extra-android-m2repository # because I'm use support library
  licenses:
    - '.+'

sudo: required

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets[0].browser_download_url')

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml


jdk:
  - oraclejdk8

install: true

before_script:
  - chmod +x gradlew

script:
 - chmod +x ./gradlew

